# Generated by Django 3.2.12 on 2022-04-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='img',
            field=models.ImageField(default='haresh', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
